### ISSUE TITLE
Remove Buttons in Columns

### ISSUE THREAD

**Issue by NathanHealea** [cs361-W16/Group21-2#3]
Remove cards should remove the bottom card on the column.
**Requirement:**
1. Check boxes should appear under each column.
2. The the delete buttons should be a submit button.
3. Each check box should have its own id or name.

**Comment by blackpatches81** [comment]
The reason I changed the name is because radio buttons we can only do one at a time and that is a waste. With checkboxes we can hit the delete button once and select one or all four of the columns if we like to delete the bottom card

**Comment by NathanHealea** [comment]
This sounds good, I like this idea because then you can remove more cards at once.

**Comment by blackpatches81** [comment]
We tried checkboxes and chose to go to just remove buttons
